#!/bin/bash

echo "# begin build properties"
echo "# autogenerated by buildinfo.sh"

echo "ro.build.id=$BUILD_ID"
echo "ro.build.display.id=$LENOVO_VERSION_EXTERNAL"
echo "ro.build.version.incremental=$BUILD_NUMBER"
echo "ro.build.version.sdk=$PLATFORM_SDK_VERSION"
echo "ro.build.version.preview_sdk=$PLATFORM_PREVIEW_SDK_VERSION"
echo "ro.build.version.codename=$PLATFORM_VERSION_CODENAME"
echo "ro.build.version.all_codenames=$PLATFORM_VERSION_ALL_CODENAMES"
echo "ro.build.version.release=$PLATFORM_VERSION"
echo "ro.build.version.security_patch=$PLATFORM_SECURITY_PATCH"
echo "ro.build.version.base_os=$PLATFORM_BASE_OS"
echo "ro.build.date=`date`"
echo "ro.build.date.utc=`date +%s`"
echo "ro.build.type=$TARGET_BUILD_TYPE"
echo "ro.build.user=$USER"
echo "ro.build.host=`hostname`"
echo "ro.build.tags=$BUILD_VERSION_TAGS"
echo "ro.build.flavor=$TARGET_BUILD_FLAVOR"
echo "ro.qq.camera.sensor=3"

#Start cui.yuehua@byd.com add for lenovo prop config
if [ "$CONFIG_BUILD_REGION" = "nec" ] ; then
  echo "ro.product.model=PC-$TARGET_DEVICE"
else
  echo "ro.product.model=Lenovo $TARGET_DEVICE"
fi
if [ "$TARGET_DEVICE" = "PB1-750N" ] ; then
  echo "ro.product.ota.model=LenovoPB1-750N_ROM_M"
elif [ "$TARGET_DEVICE" = "PB1-750M" ] ; then
  echo "ro.product.ota.model=LenovoPB1-750M_ROM_M"
elif [ "$TARGET_DEVICE" = "TB-7703F" ] ; then
  if [ "$CONFIG_BUILD_REGION" = "prc" ] ; then
    echo "ro.product.ota.model=LenovoTB-7703F_ROM_PRC"
  else
    echo "ro.product.ota.model=LenovoTB-7703F_ROM_DEV"
  fi
elif [ "$TARGET_DEVICE" = "TB-7703N" ] ; then
  echo "ro.product.ota.model=LenovoTB-7703N_ROM_DEV"
elif [ "$TARGET_DEVICE" = "TB-7703X" ] ; then
  echo "ro.product.ota.model=LenovoTB-7703X_ROM_DEV"
elif [ "$TARGET_DEVICE" = "TE507FAW" ] ; then
  echo "ro.product.ota.model=PC-TE507FAW_ROM_DEV"
else
  echo "ro.product.ota.model=LenovoDEFAULT_ROM_M"
fi

if [ "$CONFIG_BUILD_REGION" = "nec" ] ; then
  echo "ro.product.brand=NEC"
else
  echo "ro.product.brand=Lenovo"
fi

#End cui.yuehua@byd.com add for lenovo prop config




echo "ro.product.name=$PRODUCT_NAME"
echo "ro.product.device=$TARGET_DEVICE"
echo "ro.product.board=$TARGET_BOOTLOADER_BOARD_NAME"
#Start cui.yuehua@byd.com for Phoenix

if [ "$CONFIG_BUILD_REGION" = "nec" ] ; then
  echo "ro.com.google.clientidbase=android-nec"
else
  echo "ro.com.google.clientidbase=android-lenovo"
fi

#End cui.yuehua@byd.com for Phoenix
# These values are deprecated, use "ro.product.cpu.abilist"
# instead (see below).
echo "# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,"
echo "# use ro.product.cpu.abilist instead."
echo "ro.product.cpu.abi=$TARGET_CPU_ABI"
if [ -n "$TARGET_CPU_ABI2" ] ; then
  echo "ro.product.cpu.abi2=$TARGET_CPU_ABI2"
fi
echo "ro.product.cpu.abilist=$TARGET_CPU_ABI_LIST"
echo "ro.product.cpu.abilist32=$TARGET_CPU_ABI_LIST_32_BIT"
echo "ro.product.cpu.abilist64=$TARGET_CPU_ABI_LIST_64_BIT"

#Start cui.yuehua@byd.com add for lenovo prop config

if [ "$CONFIG_BUILD_REGION" = "nec" ] ; then
  echo "ro.product.manufacturer=NEC"
else
  echo "ro.product.manufacturer=LENOVO"
fi

#End cui.yuehua@byd.com add for lenovo prop config
if [ -n "$PRODUCT_DEFAULT_LOCALE" ] ; then
  echo "ro.product.locale=$PRODUCT_DEFAULT_LOCALE"
fi
echo "ro.wifi.channels=$PRODUCT_DEFAULT_WIFI_CHANNELS"
echo "ro.board.platform=$TARGET_BOARD_PLATFORM"

echo "# ro.build.product is obsolete; use ro.product.device"
echo "ro.build.product=$TARGET_DEVICE"

echo "# Do not try to parse description, fingerprint, or thumbprint"
echo "ro.build.description=$PRIVATE_BUILD_DESC"

if [ "$CONFIG_BUILD_REGION" = "nec" ] ; then
  echo "ro.build.fingerprint=NEC/$PRODUCT_NAME/$TARGET_DEVICE:$PLATFORM_VERSION/$BUILD_ID/$BUILD_NUMBER:$TARGET_BUILD_VARIANT/$BUILD_VERSION_TAGS"
else
  echo "ro.build.fingerprint=Lenovo/$PRODUCT_NAME/$TARGET_DEVICE:$PLATFORM_VERSION/$BUILD_ID/$BUILD_NUMBER:$TARGET_BUILD_VARIANT/$BUILD_VERSION_TAGS"
fi

if [ -n "$BUILD_THUMBPRINT" ] ; then
  echo "ro.build.thumbprint=$BUILD_THUMBPRINT"
fi
echo "ro.build.characteristics=$TARGET_AAPT_CHARACTERISTICS"

# whw, remove ro.bootimage.build.fingerprint from build/core/Makefile, 20160214

if [ "$CONFIG_BUILD_REGION" = "nec" ] ; then
  echo "ro.bootimage.build.fingerprint=NEC/$PRODUCT_NAME/$TARGET_DEVICE:$PLATFORM_VERSION/$BUILD_ID/$BUILD_NUMBER:$TARGET_BUILD_VARIANT/$BUILD_VERSION_TAGS"
else
  echo "ro.bootimage.build.fingerprint=Lenovo/$PRODUCT_NAME/$TARGET_DEVICE:$PLATFORM_VERSION/$BUILD_ID/$BUILD_NUMBER:$TARGET_BUILD_VARIANT/$BUILD_VERSION_TAGS"
fi

echo "# begin lenovo properties"
echo "ro.build.lenovo.version.in=$LENOVO_VERSION_INTERNAL"
echo "ro.build.lenovo.version.ex=$LENOVO_VERSION_EXTERNAL"
echo "ro.build.lenovo.sw.version=$LENOVO_SW_VERSION"
echo "ro.build.lenovo.hw.version=$LENOVO_HW_VERSION"
#Start pengchong modify for lenovo prop config
TARGET_PRODUCT
if [ "$TARGET_PRODUCT" = "msm8916_32" ] ; then
  echo "ro.lenovo.series=Lenovo PHAB"
elif [ "$TARGET_PRODUCT" = "lf7002q" ] ; then
  if [ "$CONFIG_BUILD_REGION" = "nec" ] ; then
    echo "ro.lenovo.series=LAVIE Tab E"
  else
    echo "ro.lenovo.series=Lenovo TAB3 7 Plus"
  fi
fi
#End pengchong modify for lenovo prop config

#Start add for lenovo ota prop config
echo "ro.lenovo.ota.extsd=/sdcard/"
#End add for lenovo ota prop config
echo "# end lenovo properties"

echo "# end build properties"
