LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := FreeTouchDial
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED

LOCAL_PREBUILT_JNI_LIBS := \
  @lib/armeabi/liblenovo-hwTTS.so
LOCAL_MODULE_TARGET_ARCH := arm

include $(BUILD_PREBUILT)
#########################################################
include $(CLEAR_VARS)
LOCAL_MODULE := FreeCall
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED

LOCAL_PREBUILT_JNI_LIBS := \
  @lib/armeabi/libbdEASRAndroid.v1.5.4.so
LOCAL_MODULE_TARGET_ARCH := arm

include $(BUILD_PREBUILT)
#########################################################
include $(CLEAR_VARS)
LOCAL_MODULE := FreeAnswer
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED

LOCAL_PREBUILT_JNI_LIBS := \
  @lib/armeabi/liblenovo-freeanswer-aiengine.so
LOCAL_MODULE_TARGET_ARCH := arm

include $(BUILD_PREBUILT)